In [2]:
my_list = [1,2,3]

In [3]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [11]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [12]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [27]:
np.zeros(4)

array([0., 0., 0., 0.])

In [23]:
np.zeros((4, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
np.ones(4)

array([1., 1., 1., 1.])

In [28]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [31]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
np.random.rand(5)

array([0.55551616, 0.17328923, 0.31538126, 0.34634677, 0.91533363])

In [35]:
np.random.rand(5, 5)

array([[0.3350274 , 0.97613946, 0.13674322, 0.87390384, 0.43104871],
       [0.89696013, 0.00985174, 0.24373163, 0.31248246, 0.28547445],
       [0.20907907, 0.87386694, 0.58801867, 0.80002996, 0.55094568],
       [0.80319103, 0.63390848, 0.22298907, 0.76222551, 0.49390996],
       [0.32535566, 0.96997877, 0.80130597, 0.90504023, 0.36430242]])

In [36]:
np.random.randn(2)

array([-1.01892966, -0.85865698])

In [37]:
np.random.randn(4,4)

array([[ 0.46934126, -0.23481047, -0.50681822, -0.83662029],
       [ 0.25943047,  0.61941333, -0.14415455,  0.38487894],
       [ 1.26509559,  0.59944192,  0.03447308,  0.70327299],
       [ 0.5553552 ,  0.4634157 , -1.13213582, -0.08110481]])

In [38]:
np.random.randint(1, 100)

8

In [40]:
np.random.randint(1, 100, 10)

array([ 6, 25, 38, 92, 48,  4, 20, 48, 42, 55])

In [42]:
arr = np.arange(25)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [45]:
ranarr = np.random.randint(0,50,10)

In [46]:
ranarr

array([ 7, 10,  4, 23, 31, 41, 16, 44, 23,  4])

In [47]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [52]:
arr.max()

24

In [53]:
arr.min()

0

In [54]:
ranarr.max()

44

In [55]:
ranarr.min()

4

In [56]:
ranarr.argmax()

7

In [58]:
ranarr.argmin()

2

In [59]:
arr.shape

(25,)

In [60]:
arr = arr.reshape(5,5)

In [61]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [62]:
arr.shape

(5, 5)

In [63]:
arr.dtype

dtype('int64')

In [64]:
from numpy.random import randint

In [66]:
randint(0, 10 , 5)

array([8, 1, 5, 7, 7])